<?php

/**
 * @file
 * Declares a form to test FAPI encryption.
 */

/**
 * Implementation of hook_menu().
 */
function encryptfapi_menu() {
  $items = array();

  $items['encryptfapi_test'] = array(
    'title' => t('Encrypt FAPI Test'),
    'description' => t('A test page for the Encrypt FAPI module.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('encryptfapi_test_form'),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * The form.
 */
function encryptfapi_test_form() {
  $form = array();

  $form['encryptfapi_textfield_simple'] = array(
    '#type' => 'textfield',
    '#title' => t('Textfield Simple'),
    '#default_value' => variable_get('encryptfapi_textfield_simple', ''),
    '#encrypt' => TRUE,
  );

  $form['encryptfapi_textfield_complex'] = array(
    '#type' => 'textfield',
    '#title' => t('Textfield Complex'),
    '#default_value' => variable_get('encryptfapi_textfield_complex', ''),
    '#encrypt' => array(
      'method' => 'mcrypt_rij_256',
    ),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

/**
 * Submit callback.
 */
function encryptfapi_test_form_submit($form, &$form_state) {
  foreach ($form_state['values'] as $key => $value) {
    if (strpos($key, 'encryptfapi_') === 0) {
      variable_set($key, $value);
    } 
  }
}
